### ISSUE TITLE
Cannot init recast.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [vincent/recast.js#14]
Hi, whilst looking at the API documentation and trying to use recast I cannot make an instance of it.

https://github.com/vincent/recast.js/wiki/API

```
var recast = new Recast(optionnal_path_to_worker) // Creates a new instance
```

How am I able to load multiple OBJ files for different maps.
I would like to have many maps working on a server with AI walking around using recastjs seems like my best bet so far.

I am getting the following error

```
TypeError: object is not a function
    at Object.<anonymous> (recast_test.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

From this code,

```
var Recast = require('recastjs');
var recast = new Recast();
```

It seems as if require('recast') is giving me back an object.

It does work if I only use require however I need multiple copies.

I also get the message `NavMeshQuery is not ready`.
when trying to use recast.findNearestPoint

What am I doing wrong here?

**Comment by vincent** [comment]
Hi,

Honestly I never tested multiple instances of recast.js.
Basically every Recast instance have a worker, and workers does not share memory, so I assume it's feasible without rewriting the super-duper-crappy `main.cpp` part.

The `NavMeshQuery is not ready` message is shown because you haven't `build()` it (or the build has failed)

I suggest to have a look on the [unit test](https://github.com/vincent/recast.js/blob/master/tests/recast.withworker.tests.js) to see how to use it.

If you have a test case somewhere I can have look if you want.

Cheers,

**Comment by LiamKarlMitchell** [comment]
Ah yes, I manged to look at the cpp and figure out why the message showed.

I do notice though that building is not async :( maybe I can improve this.

buildTiled does seem faster.

And that looking up pollys or nearest point will return null if none found within range of extend, something that seems should be common knowledge but was not shown in API by saying returns null if not found etc.

I suppose I could modify my server to spawn a child process for each map for recast to load into and to manage my AI. (Currently they are all on same process and I worry it will be to slow it probably should have that design anyway)

Cheers

**Comment by vincent** [comment]
Closing this, feel free to reopen if needed.
